# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::Client`.
# Please instead update this file by running `bin/tapioca dsl Api::Client`.


class Api::Client
  sig { returns(T.untyped) }
  def domain; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def domain=(value); end

  sig { returns(T.untyped) }
  def token; end

  sig { params(value: T.untyped).returns(T.untyped) }
  def token=(value); end
end
