development:
  url: <%= "postgresql://development:development@localhost:5432/gitlab_statistics_development" %>

test:
  url: <%= "postgresql://development:development@localhost:5432/gitlab_statistics_test" %>

production:
  url: <%= ENV["DATABASE_URL"] %>
